import React from 'react';
import {AbsoluteFill, Composition, Html5Audio, staticFile, useCurrentFrame, type CalculateMetadataFunction} from 'remotion';
import {Frame} from './Frame';
import {SyncChart, type SyncChartProps} from './tools/SyncChart';
import {Sheet, type SheetProps} from './tools/Sheet';
import type {Resolved} from './types';
import videos from './generated/videos.json';

type ChatProps = {d: Resolved; withAudio: boolean};

const Chat: React.FC<ChatProps> = ({d, withAudio}) => {
  const frame = useCurrentFrame();
  return (
    <AbsoluteFill>
      <Frame d={d} frame={frame} />
      {withAudio && d.audio ? (
        <Html5Audio src={staticFile(d.audio.src)} trimBefore={Math.round(d.audio.startFrom * d.fps)} volume={d.audio.volume} />
      ) : null}
    </AbsoluteFill>
  );
};

const chatMeta: CalculateMetadataFunction<ChatProps> = ({props}) => ({
  durationInFrames: props.d.durationInFrames,
  fps: props.d.fps,
  width: props.d.width,
  height: props.d.height,
});

const all = videos as unknown as Resolved[];
const placeholder = all[0];

export const Root: React.FC = () => (
  <>
    {/* One composition per video, for Remotion Studio (regenerated by `npm run rig -- studio`). */}
    {all.map((d) => (
      <Composition
        key={d.slug}
        id={d.slug.replace(/[^a-zA-Z0-9-]/g, '-')}
        component={Chat}
        defaultProps={{d, withAudio: true}}
        calculateMetadata={chatMeta}
        durationInFrames={d.durationInFrames}
        fps={d.fps}
        width={d.width}
        height={d.height}
      />
    ))}
    {placeholder ? (
      <>
        {/* Generic compositions the CLI renders with inputProps. */}
        <Composition id="Chat" component={Chat} defaultProps={{d: placeholder, withAudio: false}} calculateMetadata={chatMeta} durationInFrames={1} fps={60} width={1080} height={1920} />
        <Composition
          id="Sheet"
          component={Sheet}
          defaultProps={{d: placeholder, frames: [0], cols: 4} as SheetProps}
          calculateMetadata={({props}) => Sheet.size(props)}
          durationInFrames={1}
          fps={60}
          width={100}
          height={100}
        />
        <Composition
          id="SyncChart"
          component={SyncChart}
          defaultProps={{d: placeholder, analysis: null, from: 0, to: 10} as SyncChartProps}
          durationInFrames={1}
          fps={60}
          width={2400}
          height={900}
        />
      </>
    ) : null}
  </>
);
